{
 "title": "Fabric Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "fabric",
    "query": "SHOW TAG VALUES  WITH KEY = \"fabric\" "
   },
   {
    "name": "pod",
    "query": "SHOW TAG VALUES  WITH KEY = \"pod\" "
   },
   {
    "name": "switch",
    "query": "SHOW TAG VALUES  WITH KEY = \"node\" "
   }
  ]
 },
 "panels": [
  { "title": "Fabric Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fabric Health",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "health",
     "select": [
      [
       { "params": [ "health" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fabric Health",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "health::field" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "health",
     "query": "SELECT min(\"health\") FROM \"autogen\".\"health\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "health" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fabric Health",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "health",
     "select": [
      [
       { "params": [ "health" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ACI Fabric Health",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "health",
     "select": [
      [
       { "params": [ "health" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Faults by Severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "severity::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "faults",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Faults by Severity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "severity::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "faults",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NACK Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "faults",
     "select": [
      [
       { "params": [ "code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "ack::tag", "operator": "=", "value": "no" }
     ]
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total Encap Vlans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "aci_vlans",
     "select": [
      [
       { "params": [ "vlan" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "fabric::tag", "operator": "=~", "value": "/^$fabric$/" },
      { "condition": "AND", "key": "pod::tag", "operator": "=~", "value": "/^$pod$/" }
     ]
    }
   ]
  },
  { "title": "Interface Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Ports -> Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "total_ports",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "status::field", "operator": "=", "value": "up" },
      { "condition": "AND", "key": "fabric::tag", "operator": "=~", "value": "/^$fabric$/" },
      { "condition": "AND", "key": "pod::tag", "operator": "=~", "value": "/^$pod$/" },
      { "condition": "AND", "key": "node::tag", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Ports -> Down",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "total_ports",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "status::field", "operator": "=", "value": "down" },
      { "condition": "AND", "key": "fabric::tag", "operator": "=~", "value": "/^$fabric$/" },
      { "condition": "AND", "key": "pod::tag", "operator": "=~", "value": "/^$pod$/" },
      { "condition": "AND", "key": "node::tag", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  }
 ]
}